"""Build runtime-filter Ren'Py patch files from a translations JSON.

Output (into <out>/tl/<language_id>/):
  00_<lang>_filter.rpy   — text filter + toggle key + optional font swap
  01_<lang>_dict.rpy     — generated translation dictionary (optionally split)

Approach: config.say_menu_text_filter as a runtime translator.
No hash/ID generation needed; no game source modification. The filter
chains with any pre-existing filter (e.g. SanchoMod) instead of stomping it.

Usage:
  python build_patch.py --profile profile.json
  python build_patch.py --profile profile.json --translations my.json --out dist/ --split-size 5000
"""
import argparse
import json
import re
from pathlib import Path


def load_profile(path):
    profile_path = Path(path)
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    return profile, profile_path.parent


def py2_unicode_repr(s):
    """Emit u'...' literal that is valid in both py2 and py3 Ren'Py.
    Escape backslashes and single quotes; leave non-ASCII chars raw (file is UTF-8)."""
    s = s.replace("\\", "\\\\").replace("'", "\\'")
    # Source data carries literal \n etc. as the 2-char sequence "\\n" from the
    # rpy file; the escaping above turned that into "\\\\n". Reverse it so the
    # emitted literal keeps the original escape.
    s = s.replace("\\\\n", "\\n").replace("\\\\t", "\\t").replace('\\\\"', '\\"')
    # Escape any REAL control chars (actual newline/tab/CR) that slipped into
    # the data so they don't break the single-line string literal.
    s = s.replace("\r\n", "\\n").replace("\r", "\\n").replace("\n", "\\n").replace("\t", "\\t")
    return "u'" + s + "'"


def build_filter_rpy(profile):
    lang = profile["language_id"]
    ident = re.sub(r"\W", "_", lang)  # safe python identifier fragment
    lang_name = profile.get("language_name", lang)
    game = profile.get("game_name", "a Ren'Py game")
    toggle_key = profile.get("toggle_key", "K_F11")
    auto_set = profile.get("auto_set_language", False)
    font = profile.get("font")

    parts = []
    parts.append(f'''# {lang_name} translation runtime loader for {game}
# Generated by build_patch.py (For the Plot) - DO NOT EDIT BY HAND
#   - Press {toggle_key.replace("K_", "")} anytime to toggle {lang_name} <-> original language

init -1 python:
    _{ident}_translations = {{}}
    _{ident}_filter_calls = [0]
    _{ident}_filter_hits = [0]
    _{ident}_last_miss = [""]

    def _{ident}_say_filter(text):
        _{ident}_filter_calls[0] += 1
        try:
            if renpy.game.preferences.language == "{lang}":
                if text in _{ident}_translations:
                    _{ident}_filter_hits[0] += 1
                    return _{ident}_translations[text]
                else:
                    _{ident}_last_miss[0] = text
        except Exception:
            pass
        return text

    def _{ident}_toggle():
        cur = renpy.game.preferences.language
        new = None if cur == "{lang}" else "{lang}"
        renpy.change_language(new)
        renpy.notify(
            "Lang=%s | dict=%d | calls=%d hits=%d | filter=%s" % (
                "{lang}" if new == "{lang}" else "default",
                len(_{ident}_translations),
                _{ident}_filter_calls[0],
                _{ident}_filter_hits[0],
                "ours" if (config.say_menu_text_filter is _{ident}_say_filter
                          or getattr(config.say_menu_text_filter, "_{ident}_owned", False))
                       else "OVERRIDDEN",
            )
        )

    config.keymap["{ident}_toggle"] = ["{toggle_key}"]
    config.underlay.append(renpy.Keymap({ident}_toggle=_{ident}_toggle))

# Wrap whatever filter exists so we cooperate with mods (e.g. SanchoMod)
# instead of stomping their filter.
init 1999 python:
    def _{ident}_install_filter():
        prev = config.say_menu_text_filter
        if prev is _{ident}_say_filter:
            return
        if prev is None:
            inner = lambda t: t
        else:
            inner = prev

        # Translate FIRST (original -> {lang_name}), THEN let the mod style the
        # output. This way dict keys match the raw text the engine emits.
        def _chained(text):
            if text is None:
                return text
            t = _{ident}_say_filter(text)
            if t is None:
                t = text
            try:
                t2 = inner(t)
                return t if t2 is None else t2
            except Exception:
                return t

        # Mark our chained filter so we don't re-wrap on every callback
        _chained._{ident}_owned = True
        if getattr(prev, "_{ident}_owned", False):
            return  # already chained
        config.say_menu_text_filter = _chained

    _{ident}_install_filter()
    config.start_callbacks.append(_{ident}_install_filter)
    config.after_load_callbacks.append(_{ident}_install_filter)
''')

    if auto_set:
        parts.append(f'''
# Auto-switch to {lang_name} on first ever launch
init 2000 python:
    def _{ident}_autostart():
        if not persistent._{ident}_auto_set:
            renpy.change_language("{lang}")
            persistent._{ident}_auto_set = True
    config.start_callbacks.append(_{ident}_autostart)
''')

    parts.append(f'''
# Empty translate block registers "{lang}" as a language.
translate {lang} python:
    pass
''')

    if font:
        regular = font["regular"]
        italic = font.get("italic", regular)
        replace_fonts = font.get("replace_fonts", [])
        size_scale = font.get("size_scale", 1.0)
        base_sizes = font.get("base_sizes", {})
        default_styles = ["default", "say_dialogue", "say_thought", "say_label",
                          "namebox", "namebox_label", "button", "button_text",
                          "choice_button", "choice_button_text", "notify",
                          "notify_text", "input", "menu_choice", "menu_choice_button"]
        styles = font.get("styles", default_styles)

        replace_list = ",\n                    ".join(
            json.dumps(replace_fonts[i:i + 3])[1:-1]
            for i in range(0, len(replace_fonts), 3)
        )
        sizes_body = ", ".join(f'"{k}": {v}' for k, v in base_sizes.items())
        styles_tuple = ",\n                      ".join(
            ", ".join(f'"{s}"' for s in styles[i:i + 4])
            for i in range(0, len(styles), 4)
        )

        parts.append(f'''
# Swap the game's original fonts for {regular} whenever {lang_name} is the
# active language. Two mechanisms:
#   1. style overrides for every style that displays text
#   2. config.font_replacement_map so any missed style still falls back
init 2001 python:
    _{ident.upper()}_FONT = "{regular}"
    _{ident.upper()}_FONT_ITALIC = "{italic}"
    _{ident.upper()}_REPLACE_FONTS = [{replace_list}]

    # Per-style size scaling: adjust if the target font renders smaller or
    # larger than the originals at the same point size.
    _{ident.upper()}_SIZE_SCALE = {size_scale}
    _{ident.upper()}_BASE_SIZES = {{ {sizes_body} }}

    def _{ident}_apply_font():
        if renpy.game.preferences.language != "{lang}":
            return
        for sname in ({styles_tuple},):
            try:
                getattr(style, sname).font = _{ident.upper()}_FONT
            except Exception:
                pass
            if sname in _{ident.upper()}_BASE_SIZES:
                try:
                    getattr(style, sname).size = int(_{ident.upper()}_BASE_SIZES[sname] * _{ident.upper()}_SIZE_SCALE)
                except Exception:
                    pass

    def _{ident}_apply_font_map():
        # font_replacement_map: when these fonts would render target-language
        # chars, substitute the target font instead.
        for f in _{ident.upper()}_REPLACE_FONTS:
            for bold in (True, False):
                for italic in (True, False):
                    # Map to the real Bold (or Bold Italic) file; clear the synthetic
                    # bold/italic flags so we don't double-bold an already-bold font.
                    tgt = _{ident.upper()}_FONT_ITALIC if italic else _{ident.upper()}_FONT
                    config.font_replacement_map[(f, bold, italic)] = (tgt, False, False)

    _{ident}_apply_font_map()
    _{ident}_apply_font()
    config.start_callbacks.append(_{ident}_apply_font)
    config.after_load_callbacks.append(_{ident}_apply_font)
    # Hook language change to re-apply
    _prev_change_language = renpy.change_language
    def _{ident}_change_language(lang, force=False):
        result = _prev_change_language(lang, force) if force else _prev_change_language(lang)
        _{ident}_apply_font()
        return result
    renpy.change_language = _{ident}_change_language
''')

    return "".join(parts)


def build_dict_rpy(translations, ident, lang_name, chunk=None):
    """Yield (filename_suffix, content) for one or more dict files."""
    items = list(translations.items())
    if not chunk or chunk <= 0:
        chunk = len(items) or 1
    n_files = (len(items) + chunk - 1) // chunk if items else 1
    for fi in range(max(n_files, 1)):
        part = items[fi * chunk:(fi + 1) * chunk]
        lines = [
            f"# {lang_name} translation dictionary — auto-generated"
            + (f" (part {fi + 1}/{n_files})" if n_files > 1 else "") + "\n",
            "# DO NOT EDIT BY HAND\n\n",
            "init 0 python:\n",
            f"    _{ident}_translations.update({{\n",
        ]
        for eng, tr in part:
            lines.append(f"        {py2_unicode_repr(eng)}: {py2_unicode_repr(tr)},\n")
        lines.append("    })\n")
        yield fi, "".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Build a runtime-filter Ren'Py translation patch")
    ap.add_argument("--profile", required=True, help="profile.json")
    ap.add_argument("--translations", help="translations JSON (overrides profile progress_file)")
    ap.add_argument("--out", help="output dir (overrides profile output_dir); patch goes to <out>/tl/<lang>/")
    ap.add_argument("--split-size", type=int, default=0,
                    help="max entries per dict file (0 = single file)")
    args = ap.parse_args()

    profile, base = load_profile(args.profile)
    lang = profile["language_id"]
    ident = re.sub(r"\W", "_", lang)
    lang_name = profile.get("language_name", lang)

    trans_path = Path(args.translations) if args.translations else base / profile.get("progress_file", "translations.json")
    out_root = Path(args.out) if args.out else base / profile.get("output_dir", "output")
    out_dir = out_root / "tl" / lang
    out_dir.mkdir(parents=True, exist_ok=True)

    translations = json.loads(trans_path.read_text(encoding="utf-8"))
    print(f"Building patch with {len(translations)} translations...")

    filter_path = out_dir / f"00_{ident}_filter.rpy"
    filter_path.write_text(build_filter_rpy(profile), encoding="utf-8")
    print(f"Wrote {filter_path}")

    for fi, content in build_dict_rpy(translations, ident, lang_name, args.split_size):
        dict_path = out_dir / f"{fi + 1:02d}_{ident}_dict.rpy"
        dict_path.write_text(content, encoding="utf-8")
        print(f"Wrote {dict_path}")

    print(f"\nDeploy: copy {out_dir} into the game's game/tl/ folder "
          f"(and the target font files into game/).")


if __name__ == "__main__":
    main()
